# docker-compose for nfs-client
#
version: "2.4"
services:

  zmq-friend-1:
    image: phlax/zmq
    networks:
    - zmq
    expose:
    - 2323
    environment:
    - ZMQ_APP_0=ctrl.zmq.rpc.ZMQRPCServer tcp://*:2323

  zmq-friend-2:
    image: phlax/zmq
    networks:
    - zmq
    environment:
    - CFG_CTRL=/app/controller.conf
    - ZMQ_APP_0=ctrl.zmq.rpc.ZMQRPCClient tcp://zmq-friend-1:2323 stop_service foo
    volumes:
    - ./controller.conf:/app/controller.conf

networks:
  zmq:
