# docker-compose for nfs-client
#
version: "2.4"
services:

  zmq-friend-1:
    image: phlax/zmq
    networks:
    - zmq
    expose:
    - 2323
    environment:
    - ZMQ_APP_0=ctrl.socket.server.ZMQSocketServer tcp://*:2323
    volumes:
    - ${PWD}/example/src:/app/src

  zmq-friend-2:
    image: phlax/zmq
    networks:
    - zmq
    environment:
    - ZMQ_APP_0=ctrl.socket.client.ZMQSocketClient tcp://zmq-friend-1:2323
    volumes:
    - ${PWD}/example/src:/app/src

networks:
  zmq:
