# https://travis-ci.org/#!/phlax/zmq
dist: trusty
sudo: true
language: python
services:
  - docker

before_install:
  - "echo '{\"storage-driver\": \"overlay2\"}' | sudo tee /etc/docker/daemon.json"
  - sudo service docker restart

install:
  - pip install -U docker-compose
  - docker-compose build zmq

script:

  # set the environment
  - echo "COMPOSE_FILE=./example/docker-compose.yml" > ./.env

  - docker-compose up -d zmq-friend-1
  - docker-compose up -d zmq-friend-2

  - docker-compose logs zmq-friend-1
  - docker-compose logs zmq-friend-2

  # run a command in the client
  - docker-compose -f example/docker-compose.yml exec zmq-friend-2 /app/bin/ctrl zmq rpc tcp://zmq-friend-1:2323 stop_service bar

  # run a command with the client
  - docker-compose stop zmq-friend-2
  - docker-compose -f example/docker-compose.yml run --rm zmq-friend-2 /app/bin/ctrl zmq rpc tcp://zmq-friend-1:2323 stop_service baz

  - docker-compose logs zmq-friend-2

  # stop the server
  - docker-compose stop zmq-friend-1
  - docker-compose logs zmq-friend-1

after_success:

  - docker-compose build zmq
  - docker login -u phlax -p "$DOCKER_PASSWORD"
  - docker push phlax/zmq
